INSERT INTO Category (name) VALUES ('Bíblias');
INSERT INTO Category (name) VALUES ('Feminino');
INSERT INTO Category (name) VALUES ('Masculino');
INSERT INTO Category (name) VALUES ('Livros');
INSERT INTO Category (name) VALUES ('Presentes');
INSERT INTO Category (name) VALUES ('Produtos em destaque');
INSERT INTO Category (name) VALUES ('Promoções');

INSERT INTO about_us (description, imageurl) VALUES ('No mercado de Itajaí - SC desde 1997, a Lírio dos Vales - Moda Evangélica está sempre trazendo o que há de melhor no seguimento evangélico (moda feminina e masculina, e artigos evangélicos). Venha nos conhecer! (Endereço no rodapé do site.)', 'https://i.imgur.com/6bYbUxw.png');

INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia de Estudo da Mulher Sábia, Harpa Avivada e Corinhos, P/ Bolsa, Rosa', 105.0, null, 'em até 4x de R$ 26,25 s/ juros no cartão', null, 'https://i.imgur.com/qwsGI0r.png', 'Bíblia Sagrada, com a linguagem na versão ARC (Revista Corrigida) de João Ferreira de Almeida. Sendo a versão mais utilizada pelos evangélicos do Brasil. Com sua fidelidade traduzida dos textos originais pelo missionário português João Ferreira de Almeida, esta obra tem como destaque sua linguagem elegante e culta.<br /><br /><b>Letras:</b> Normais<br /><b>Capa:</b> PU Rosa<br/><b>Índice:</b> Não<br /><b>Páginas:</b> 1.544<br /><b>Editora:</b> CPP');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia de Estudo da Mulher Sábia, Harpa Avivada e Corinhos, P/ Bolsa, Vermelha', 105.0, null, 'em até 4x de R$ 26,25 s/ juros no cartão', null, 'https://i.imgur.com/cQyqXrk.png', 'A Bíblia de Estudo da Mulher Sábia com Harpa Avivada e Corinhos foi pensada e desenvolvida especialmente para o público feminino. Esta Bíblia de estudo contém aplicações e estudos de acordo com cada versículo ou livro da Bíblia.');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia de Estudo da Mulher Sábia, Harpa Avivada e Corinhos, Preto', 145.0, 135.0, 'em até 4x de R$ 33,75 s/ juros no cartão', null, 'https://i.imgur.com/B6KVA7h.png', 'A Bíblia de estudo da Mulher Sábia foi feita especialmente para o público feminino, contém aplicações e estudos de acordo com cada versículo ou livro da Bíblia, tornando uma leitura mais fácil. Contém textos para você meditar com várias palavras edificantes e aborda questões interessantes de acordo com cada mulher, um exemplo: a mulher como mãe, a mulher como sogra, a mulher como nora, a mulher como amiga e entre outros.<br />Recursos<br />Aplicação pessoal<br />Leitura<br />Estudo<br />Meditação<br /><br /><b>Tradução:</b> João de Almeida<br/><b>Letras:</b> Grandes');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia da Mulher, Rosa', 135.0, 125.0, 'em até 4x de R$ 31,25 s/ juros no cartão', null, 'https://i.imgur.com/TSuGmm0.png', 'Há mais de dez anos fazendo sucesso entre o público feminino, a Bíblia da Mulher foi totalmente repaginada: ganhou novos formatos, capas ainda mais charmosas e uma diagramação primorosa. Tudo isso para conferir ainda mais destaque a seus consagrados estudos, preparados por mulheres de diferentes países, faixas etárias e nações. Além deste valioso material focado em áreas de interesse da mulher, esta obra contém recursos variados que contribuem para a aplicação da Palavra de Deus no dia a dia da mulher. Com impressão em duas cores, a nova edição é apresentada com 11 modelos diferentes de capa. Recursos - Notas e referências bíblicas - Artigos teológicos sobre a mulher na arqueologia bíblica, fé e vida prática, mulheres e crianças na narrativa bíblica, e o cuidado de Deus pelas mulheres - Citações inspiradoras de mulheres cristãs consagradas - Concordância temática - Introdução e esboço a cada livro bíblico - Mais de 100 retratos com o perfil de mulheres da Bíblia - Mais de 320 tópicos sobre temas como ministério feminino, o papel da mulher na sociedade moderna, carreira profissional, educação de filhos, família, entre outros - Mapas e quadros em meio ao texto bíblico - Notas explicativas sobre termos e passagens bíblicas difíceis - Ponto de Vista - quadros sobre a importância de ler e estudar a Palavra de Deus - Moedas e medidas na Bíblia - Quadros ilustrados sobre a flora bíblica - Mapas coloridos Impressão em duas cores.<br /><br /><b>Autor:</b> Sociedade Bíblica do Brasil<br /><b>Páginas: </b> 1.1927<br /><b>Idioma: </b> Português<br /><b>Acabamento: </b> Flexível');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia Harpa Cristã, Letra Grande, Letras Vermelhas e Auxílios para o Leitor', 110.3, null, 'em até 4x de R$ 27,57 s/ juros no cartão', null, 'https://i.imgur.com/X9stOMS.jpg', 'Bíblia Sagrada com Harpa Cristã e capa semiflexiveis.');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia de Estudos e Sermões de C.H. Spurgeon, RBC', 265.0, 255.0, 'em até 4x de R$ 63,75 s/ juros no cartão', null, 'https://i.imgur.com/we5S5qI.png', 'A Bíblia de estudos de Charles H. Spurgeon é resultado de um cuidadoso trabalho de pesquisa e leitura nos mais de 3.500 sermões produzidos por Charles Haddon Spurgeon ao longo de seus mais de 40 anos de ministério pastoral. A seleção dos textos baseou-se na diversificação de assuntos, abordagens e necessidades da Igreja contemporânea. Apesar de escritos há mais de um século, os temas se mantêm relevantes e a profundidade das reflexões desafiam o leitor atual ao apego às Escrituras Sagradas, à devoção e ao compromisso com Deus. Os pregadores e professores apreciarão as alusões homiléticas em praticamente cada versículo e as considerações provocativas que despertam e inspiram. Este esplêndido clássico será amplamente apreciado como ferramenta de estudo pessoal no livro de Salmos ou para preparação de sermões e aulas.<br /><br /><b>Formato:</b> Brochura<br /><b>Editora:</b> Publicações RBC Pão Diário<br /><b>Idioma: </b> Português<br /><b>Autor: </b> C H SPURGEON<br /><b>Páginas:</b> 1.664');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia do Pregador Pentecostal, C/ Índice, Atualizada', 288.5, null, 'em até 4x de R$ 72,12 s/ juros no cartão', null, 'https://i.imgur.com/9y7p5eG.jpg', 'A renomada Bíblia do Pregador Pentecostal, que traz sermões prontos junto ao texto bíblico, agora é apresentada com texto bíblico na Nova Almeida Atualizada (NAA) (NAA). O principal objetivo da publicação é colocar à disposição de todos os obreiros uma ferramenta prática e de conteúdo rico para o exercício do ministério cristão. Para isso, reúne 1.002 sermões bíblicos que foram especialmente elaborados, atualizados e complementados pelo teólogo e pastor Erivaldo de Jesus. Cada sermão é subdividido em variados tópicos e referências bíblicas acerca do tema abordado e possui os três elementos fundamentais do princípio da homilética, que é a arte de pregar: introdução, explanação e conclusão. As introduções a cada livro bíblico também foram atualizadas e complementadas e incluem recursos indicando a obra de Deus, de Jesus e do Espírito Santo em cada livro. A edição traz ainda um curso básico de Teologia, composto de 12 matérias teológicas, que dará uma pequena noção do que é Teologia e sua importância para o crescimento espiritual, intelectual e bíblico de todos os estudantes da Bíblia Sagrada. Como novidade, a obra apresenta índice dos sermões e índice por assunto, que auxiliam na escolha de pregações voltadas aos mais diversos públicos e ocasiões. Além disso, tem um Manual de Cerimônias, com explicações e orientações para dirigir o culto e celebrações de eventos especiais, além de sugestões de sermões a serem usados em cada ocasião. Em uma sociedade em que as pessoas vivem sempre correndo e com o tempo cada vez mais escasso para realizar todas as tarefas que têm de desempenhar, esta edição da Bíblia Sagrada tem o objetivo de facilitar a vida de pastores e pregadores, oferecendo um caminho, uma luz, para que desenvolvam os temas que desejam trabalhar em seus sermões, de uma forma prática e rápida. <b>Sobre o texto bíblico:</b> Lançada pela SBB em 2017, a NAA é resultado de uma profunda revisão da consagrada tradução Almeida Revista e Atualizada, e apresenta um texto clássico com uma linguagem atual, seguindo a norma padrão do português escrito e falado no Brasil.Sobre o Pr. Erivaldo de Jesus: Autor de nove livros e com grande experiência e conhecimento na área bíblica, o Pr. Erivaldo de Jesus é doutor em Teologia e ministro do Evangelho. Bacharel em Direito, é professor de Teologia Sistemática e conferencista internacional. É pastor filiado à Convenção Fraternal das Assembleias de Deus do Estado de São Paulo (Confradesp) e à Convenção Geral das Assembleias de Deus no Brasil (CGADB).');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia da Pregadora Pentecostal, Branca', 245.92, 232.22, 'em até 4x de R$ 58,05 s/ juros no cartão', null, 'https://i.imgur.com/Wd034WV.png', 'Versão feminina da Bíblia do Pregador Pentecostal, esta é uma ferramenta indispensável para o exercício do ministério da mulher cristã. Além de todos os recursos contidos na consagrada obra, a Bíblia da Pregadora Pentecostal vem com um encarte especial que cita as mulheres de cada livro da Bíblia, quem elas foram, o que fizeram e suas influências, com referência de onde encontrar suas histórias nas Escrituras Sagradas.');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia c/ Espaço para Anotações, Floral Rosa, Espiral', 105.0, null, 'em até 4x de R$ 26,25 s/ juros no cartão', null, 'https://i.imgur.com/OccYQih.jpg', 'Bíblia Sagrada, com a linguagem na versão ARC (Revista Corrigida) de João Ferreira de Almeida. Sendo a versão mais utilizada pelos evangélicos do Brasil. Com sua fidelidade traduzida dos textos originais pelo missionário português João Ferreira de Almeida, esta obra tem como destaque sua linguagem elegante e culta. Agora a mais nova edição da Casa Publicadora Paulista, apresentamos a vocês a Bíblia com Espaço para Anotações Pautados, com diferenciais exclusivos e também muito procurados, a bíblia com espaço para anotações contém Harpa, Corinhos e Índice lateral.');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bíblia c/ Espaço para Anotações, Leão Pintura, Espiral', 105.0, null, 'em até 4x de R$ 26,25 s/ juros no cartão', null, 'https://i.imgur.com/mdsiTFr.jpeg', 'Bíblia Sagrada, com a linguagem na versão ARC (Revista Corrigida) de João Ferreira de Almeida. Sendo a versão mais utilizada pelos evangélicos do Brasil. Com sua fidelidade traduzida dos textos originais pelo missionário português João Ferreira de Almeida, esta obra tem como destaque sua linguagem elegante e culta. Agora a mais nova edição da Casa Publicadora Paulista, apresentamos a vocês a Bíblia com Espaço para Anotações Pautados, com diferenciais exclusivos e também muito procurados, a bíblia com espaço para anotações contém Harpa, Corinhos e Índice lateral.');

INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Rosalie, Vestido Preto e Branco Tubinho', 59.99, null, 'em até 2x de R$ 30,00 s/ juros no cartão', 'P, M, G e GG', 'https://i.imgur.com/xYSlxuQ.jpeg', 'Vestido em malha de algodão com recorte na frente e mangas em malha flamê. Modelo com decote redondo, mangas 3/4 com franzidos nos ombros e recorte centralizado nas costas. Possui botões decorativos na frente.</br></br><b>Comprimento:</b> Midi</br><b>Modelagem:</b> Justo</br><b>Modelo:</b> Tubinho');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Bolsa, Marrom', 104.5, null, 'em até 2x de R$ 52,25 s/ juros no cartão', null, 'https://i.imgur.com/Dp9LVqj.jpeg', 'Bolsa Feminina, marrom, top!');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Camisa Masculina Gola Polo, Verde', 39.9, 29.9, 'em até 2x de R$ 14,99 s/ juros no cartão', 'P e M', 'https://i.imgur.com/M7EuAB5.jpeg', 'Camisa Masculina Gola Polo, top!');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Blusa Franzida, Floral, Verde', 42.35, null, 'em até 2x de R$ 21,17 s/ juros no cartão', 'P e M', 'https://i.imgur.com/4AHgfAi.jpeg', 'Blusa Franzida, Floral, Verde, top!');
INSERT INTO Product (name, price, promotional_price, payment_terms, sizes, imageurl, description) VALUES ('Saia Longa, Floral, Beje', 71.14, 52.10, 'em até 2x de R$ 26,05 s/ juros no cartão', 'P, M e G', 'https://i.imgur.com/pVc75ah.jpeg', 'Saia Longa, Floral, Beje, top!');

INSERT INTO product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO product_category (product_id, category_id) VALUES (10, 1);

INSERT INTO product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO product_category (product_id, category_id) VALUES (14, 2);
INSERT INTO product_category (product_id, category_id) VALUES (15, 2);

INSERT INTO tb_user (user_Name, email, password) VALUES ('Administrador', 'liriodosvales_2009@hotmail.com', '$2a$10$.v05InGkIEBeTrT353DLweSQxTpDLKAiD1..9S0XtQZFyXhXMnsxi');
